version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-1

phases:
  pre_build:
    commands:
      - echo Starting build...

  build:
    commands:
      - echo Build started on `date`
      - apt update
      - mkdir -p /tmp/clam
      - apt-get install clamav libnet-dns-perl -y
      - perl clamdownloader.pl
      - ls -la /tmp/clam
      - aws s3 sync /tmp/clam s3://<your-bucket>
      - echo Done uploading to S3 `date`
